[project]
name = "zh-air-quality"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "alfell", email = "ale_feller@hotmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
zh-air-quality = "zh_air_quality:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
