[tox]
env_list = integration

[testenv]
runner = uv-venv-lock-runner
dependency_groups = dev
commands = 
    pytest tests/{env_name} \
        --cov=zh_air_quality \
        --cov-report=term-missing \
        --cov-report=xml:reports/coverage-{env_name}.xml \
        --junitxml=reports/junit-{env_name}.xml \
        {posargs}